### ISSUE TITLE
Able to access the GPS data from this library?

### ISSUE THREAD

**Issue by zack-404** [GeoTecINIT/BackgroundSensors#8]
Currently, I'm developing an app can send gyro and acc data from the sensor. in the background This library can do it pretty well. However, after observing the log, I found that there is printing the location. I wonder am I able to access that location signal? Or how can I access this API?

The log is shown as below.

```
I/flutter (30854): Response Body: {"success":true,"data":{"accuracy":0.0,"speed":0.0,"speed_accuracy":0.0,"heading":0.0,"altitude":0.0,"time":1716000618259,"lat":22.638821,"lon":120.321957}}
```

**Comment by matey97** [comment]
Hi @zack-404, 

First of all, thanks for using this library. Right now, the library doesn't support the access to the device's location, although I might implement it in the future. Therefore, I suspect that log might come from other library or flutter package that your app is using. Otherwise, it might be a system log. Anyway, I'm sure that log doesn't come from this library.

**Comment by zack-404** [comment]
Thanks for your replying. I have check one more time, and I find out that this is the message from the other app. And have a great appreciate to your library. It plays an important role in my project.
